[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environments]
  [environments.production]
    PORT = 3000
    NODE_ENV = "production"