export { Login } from "./login/Login";
export { UnderDevelopment } from "./UnderDevelopment";
export { Dashboard } from "./admin/Dashboard";
export { CouponSeriesCreate } from "./admin/coupons/CouponSeriesCreate";
export { Admin } from "./admin/coupons/Admin";
export { CouponsList } from "./admin/coupons/CouponsList";
// Anciens exports supprimés - maintenant dans ./admin/ndrs/
export { default as PdfPreview } from "./admin/PdfPreview";
export { Prospects } from "./prospects/Prospects";
export { ProspectDetails } from "./prospects/ProspectDetails";
export { Clients } from "./clients/Clients";
export { ClientDetails } from "./clients/ClientDetails";
export { Professeurs } from "./professeurs/Professeurs";
export { ProfesseurDetails } from "./professeurs/ProfesseurDetails";
export { ProfesseurDocuments } from "./professeurs/ProfesseurDocuments";
export { ProfesseurDashboard } from "./professeur/ProfesseurDashboard";
export { MesRendezVous } from "./professor/MesRendezVous";
export { MesDocuments } from "./professor/MesDocuments";
export { MonProfil } from "./professor/MonProfil";
export { default as MesChoix } from "./professor/MesChoix";
export { MesCoupons } from "./professor/MesCoupons";
export { FichePaie } from "./professor/FichePaie";
export { MaDeclaration } from "./professor/MaDeclaration";
export { MesEleves } from "./professor/MesEleves";
export { ProfessorLayout } from "./professor/ProfessorLayout";
export { AdminLayout } from "./admin/AdminLayout";
