name: Deploy to GitHub Pages

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd abc-cours-crm
          npm ci

      - name: Build
        env:
          VITE_API_URL: https://crm-abc-cours-production.up.railway.app/api
        run: |
          cd abc-cours-crm
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: abc-cours-crm/dist
